source 'https://rubygems.org'

gem 'rails', '4.1.4'
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'
gem "therubyracer"
gem "less-rails"
gem 'twitter-bootstrap-rails'
gem 'devise'
gem 'better_errors', :groups => [:development]
gem "binding_of_caller"
gem 'mailjet', :git => 'https://github.com/mailjet/mailjet-gem.git'
gem 'twilio-ruby'

gem 'nokogiri'
# gem 'open-uri'
# gem 'spf'
gem 'rubypython'
gem 'encryptor'
# gem 'libpayroll', :path => '/Users/tylernappy/desktop/hackcc/chess_parser/payroll_calculator'

#may take this out
# gem 'localtunnel'
# Use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.1.2'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano', group: :development

gem 'em-websocket'

# Use debugger
gem 'httparty'

group :production do
  gem 'pg'
  gem 'rails_12factor'
end

group :development, :test do
  # gem 'mysql2'
  gem 'sqlite3'
  gem 'rspec-rails'
  gem 'factory_girl_rails'
  gem 'debugger'
  gem 'dotenv-rails'
end

group :doc do
  gem 'sdoc', require: false
end
